"""Curate the Hugging Face profile: privatize legacy 2023 legal-QA repos and delete
the genuinely empty/byproduct ones. Explicit hardcoded lists (no wildcards), dry-run
by default; pass --apply to execute. Deletes are IRREVERSIBLE.

Decision (2026-06-10, user): privatize the real legacy repos (reversible, keeps any
download history), delete only the empty model + the two private autotrain byproducts
+ the throwaway "Trial_" Space.

  C:\\comet_venv\\Scripts\\python.exe scripts/hf_curate.py           # dry-run (default)
  C:\\comet_venv\\Scripts\\python.exe scripts/hf_curate.py --apply   # execute
"""
import argparse
import os
import time
from pathlib import Path

from huggingface_hub import HfApi

# (repo_type, repo_id) -> made private (hidden from public profile, reversible).
PRIVATIZE = [
    ("model", "PyaeSoneK/LlamaV2LegalFineTuned"),
    ("model", "PyaeSoneK/finetuned_pythia-2.8b-deduped_legal"),
    ("model", "PyaeSoneK/Fine_Tuned_Pythia_smallest_140_legal"),
    ("model", "PyaeSoneK/pythia_70m_legalQA"),
    ("dataset", "PyaeSoneK/LegalFewShot"),
    ("space", "PyaeSoneK/legalQAcustom"),
    ("space", "PyaeSoneK/chatchat"),
]
# (repo_type, repo_id) -> deleted (empty / machine-generated byproduct / throwaway).
DELETE = [
    ("model", "PyaeSoneK/LegalQAfewshot"),
    ("dataset", "PyaeSoneK/autotrain-data-legalqa"),
    ("dataset", "PyaeSoneK/autotrain-data-legalqacustom"),
    ("space", "PyaeSoneK/Trial_Seallm_with_mydata"),
]


def load_env_token() -> None:
    """Export HF_TOKEN from the repo .env."""
    for key in ("HF_TOKEN", "HUGGINGFACE_HUB_TOKEN"):
        if os.environ.get(key):
            return
    env = Path(".env")
    if not env.exists():
        return
    for line in env.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if line.startswith(("HF_TOKEN=", "HUGGINGFACE_HUB_TOKEN=")):
            val = line.partition("=")[2].strip().strip('"').strip("'")
            if val:
                os.environ["HF_TOKEN"] = os.environ["HUGGINGFACE_HUB_TOKEN"] = val
                return


def _retry(label: str, fn, attempts: int = 6):
    """Network op with backoff (HF API resets connections on this network)."""
    last = None
    for i in range(1, attempts + 1):
        try:
            return fn()
        except Exception as exc:
            last = exc
            print(f"    [{label}] attempt {i}/{attempts}: {type(exc).__name__}: "
                  f"{str(exc)[:100]}", flush=True)
            time.sleep(min(6 * i, 45))
    raise last


def privatize(api: HfApi, repo_type: str, repo_id: str, apply: bool) -> None:
    """Set a repo private (reversible)."""
    if not apply:
        print(f"  [dry-run] would PRIVATIZE {repo_type}: {repo_id}")
        return
    _retry("privatize", lambda: api.update_repo_settings(
        repo_id=repo_id, repo_type=repo_type, private=True))
    print(f"  privatized {repo_type}: {repo_id}")


def delete(api: HfApi, repo_type: str, repo_id: str, apply: bool) -> None:
    """Delete a repo (IRREVERSIBLE)."""
    if not apply:
        print(f"  [dry-run] would DELETE {repo_type}: {repo_id}")
        return
    _retry("delete", lambda: api.delete_repo(
        repo_id=repo_id, repo_type=repo_type, missing_ok=True))
    print(f"  DELETED {repo_type}: {repo_id}")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--apply", action="store_true", help="execute (default: dry-run)")
    args = ap.parse_args()

    load_env_token()
    api = HfApi()
    mode = "APPLY" if args.apply else "DRY-RUN"
    print(f"=== HF curate ({mode}) ===")
    print(f"-- privatize ({len(PRIVATIZE)}) --")
    for rt, rid in PRIVATIZE:
        privatize(api, rt, rid, args.apply)
    print(f"-- delete ({len(DELETE)}) --")
    for rt, rid in DELETE:
        delete(api, rt, rid, args.apply)
    print("done." if args.apply else "dry-run complete; re-run with --apply to execute.")


if __name__ == "__main__":
    main()
